name: coco_mobile_explorer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  retrofit: 3.0.1+1
  get_it: 7.2.0
  json_annotation: ^4.4.0
 # intl: ^0.17.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: 4.0.1
  hive_generator: ^1.1.2
  build_runner: 2.1.7
  json_serializable: 6.1.5

flutter:
  uses-material-design: true